import { Geist, Geist_Mono } from "next/font/google";
import demandeIcon from "@/assets/notebook.png";
import stageIcon from "@/assets/work.png";
import offreIcon from "@/assets/archive.png";
import stagiaireIcon from "@/assets/user.png";
import staffIcon from "@/assets/staff.png";
import logo from "@/assets/image.png";
import NavItem from "@/components/NavItem";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const navItems = [
    {
      text: "Demandes",
      icon: demandeIcon,
      link: "/demande",
    },
    {
      text: "Stages",
      icon: stageIcon,
      link: "/stage",
    },
    {
      text: "Offres",
      icon: offreIcon,
      link: "/offre",
    },
    {
      text: "Stagiaires",
      icon: stagiaireIcon,
      link: "/stagiaire",
    },
    {
      text: "Staff",
      icon: staffIcon,
      link: "/staff",
    },
  ];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        {/* main container */}
        <div className="flex h-screen overflow-hidden">
          {/* sidebar - fixed height and scrollable */}
          <div className="w-64 bg-blue-800 flex flex-col flex-shrink-0">
            <div className="flex flex-col h-full">
              {/* Logo section */}
              <div className="p-6">
                <Link href="/" className="block">
                  <Image
                    className="mx-auto rounded-lg p-1 bg-white hover:opacity-80 transition-opacity duration-200 cursor-pointer"
                    src={logo}
                    alt="logo"
                    width="150"
                    height="150"
                  />
                </Link>
              </div>
              
              {/* Navigation section - scrollable if needed */}
              <div className="flex-1 overflow-y-auto">
                <div className="px-4 pb-4">
                  {navItems.map((item, idx) => {
                    return <NavItem item={item} key={idx} />;
                  })}
                </div>
              </div>
            </div>
          </div>
          
          {/* Main content area - scrollable */}
          <div className="flex-1 overflow-y-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
