import { Geist, Geist_Mono } from "next/font/google";
import demandeIcon from "@/assets/notebook.png";
import stageIcon from "@/assets/work.png";
import offreIcon from "@/assets/archive.png";
import stagiaireIcon from "@/assets/user.png";
import staffIcon from "@/assets/staff.png";
import NavItem from "@/components/NavItem";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const navItems = [
    {
      text: "Demandes",
      icon: demandeIcon,
    },
    {
      text: "Stages",
      icon: stageIcon,
    },
    {
      text: "Offres",
      icon: offreIcon,
    },
    {
      text: "Stagiaires",
      icon: stagiaireIcon,
    },
    {
      text: "Staff",
      icon: staffIcon,
    },
  ];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        {/* main container */}
        <div className="flex flex-row">
          {/* sidebar */}
          <div className="h-screen w-64 bg-blue-800 ">
            <h1 className="h-32 w-32 bg-white pl">logo</h1>
            <div className="mt-10">
              {navItems.map((item, idx) => {
                return <NavItem item={item} key={idx} />;
              })}
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
